### ISSUE TITLE
FSU Promotions

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#125]
What client likes

![wvu_promotions](https://user-images.githubusercontent.com/26416133/32457522-6cfd0f9c-c2f7-11e7-8f31-89a5d29316de.jpg)

**Comment by adavila17** [comment]
![fsu_promotions](https://user-images.githubusercontent.com/26416133/32460619-5db3b414-c301-11e7-91f4-8ba2a03b9790.jpg)

**Comment by adavila17** [comment]
Test Temp ID: 714

**Comment by ValentineRain** [comment]
I think the only things that need to be modified here are:

1. There should not be a background step (it doesn't do anything)
2. The "Season Tip Off" text of your preview image is defaulting to transparent with a colored stroke, rather than solid, which doesn't match your preview.

![duck](https://user-images.githubusercontent.com/26412274/32518357-4d96435e-c3d7-11e7-9ffc-4fb0b5ab1d1e.png)

No other issues.

**Comment by adavila17** [comment]
Yeah forgot the bg thing.
Can't help the text thing they have a version that does both outlines and/or fills for the text non issue on our end.

**Comment by adavila17** [comment]
preview add @lisajohnson11 inform client i suppose. I r closing
