### ISSUE TITLE
FSU Make ScheduleShot Dynamic

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#28]
Template #617 needs dynamic drop down for 6 - 17 games. Labeled "Number of Games".

If there is an even number of games, like 6 games, there will be two rows with the same number of drop zones centered horizontally on the template. 

![ss_fsu_scheduleshot_v1 even](https://user-images.githubusercontent.com/26416133/28972618-5b7ca0cc-78fe-11e7-8bcb-048a7fe45373.jpg)

If there is an odd number of games, like 7 games, the top row will have one more game drop zone than the bottom row centered horizontally on the template.

![ss_fsu_scheduleshot_v1 odd](https://user-images.githubusercontent.com/26416133/28972641-6c945c9c-78fe-11e7-9b76-a052d8aecc15.jpg)

**Comment by ericmoore1** [comment]
This item is ready for review.

**Comment by adavila17** [comment]
@Aubron please merge so we can tag Val to test.

**Comment by ValentineRain** [comment]
Whoops, so this actually requires a PR, not a merge.

**Comment by ValentineRain** [comment]
Just adding that I found the pull request, it's [this one](https://github.com/Aubron/scoreshots/pull/233).
These will go faster in the future if they're linked in the thread!

**Comment by ValentineRain** [comment]
This may be a non-issue, and I apologize if so. But I noticed that the logo arrangements here are sort of "mirror-reversed" from the preview. Specifically, that the upper row is aligned slightly left of the lower row, rather than the other way around.

Since I'm not in communication with FSU, I don't know if they revised or asked for this. If they did, cool, otherwise, this isn't quite to spec.

![untitled](https://user-images.githubusercontent.com/26412274/29431418-dc35856e-8365-11e7-9441-67c41efaa81e.png)

I am still testing this in terms of functionality. Sorry to be nit picky.

**Comment by ValentineRain** [comment]
Found a few other issues. Namely that logos added to the team drop zones, while clipped properly, are appearing off-target. Additionally, the user is going to have a tremendously difficult time repositioning any of them, because despite being on a layer behind the logos, the central player cutouts always seem to take priority when that area is clicked. It's not a great experience.

[Here's a video](https://drive.google.com/a/imsports.com/file/d/0BwH5-fbQakiyR0dWY2d2NjFKZUk/view?usp=sharing) of both issues occurring. This is in Chrome.

**Comment by ValentineRain** [comment]
I ran into one final bug where the bottom row of team text (and only that row) was unselectable. I can't reproduce it, so don't worry about it right now, but I'll want to return to it on my next pass.

Tagging @ericmoore1 back in to take a look at this when he has a chance.

**Comment by adavila17** [comment]
The original from which dev team pulled from does not have this issue. Logos drop in as they should. Dunno what's going on.

**Comment by ericmoore1** [comment]
This is now ready for testing. Thanks @Aubron  & @kelvin-im .
Please see https://github.com/Aubron/scoreshots/compare/master...template-617

**Comment by ValentineRain** [comment]
Flagging this for testing.
Sorry this sat for a week. I didn't know.

**Comment by ValentineRain** [comment]
The logo clipping issue is fixed! Unfortunately there are still a few persisting behaviors that need to be addressed.

- If the user adds logos by double clicking the media manager after reducing the team count, they can add logos to spaces that don't exist. Pictured here is a 13 game template where I was able to add logos for spaces 14-17. This behavior occurs in all browsers.

![bg](https://user-images.githubusercontent.com/26412274/29839758-6ea38eee-8ccd-11e7-9462-a67f761ec517.png)

- Also, the positioning for the individual games is still incorrect in the way described above, for any even number of games. Though its correct to center them this way, it looks like the top row is meant to be stacked slightly to the left, rather than slightly to the right, of the bottom row. Illustrating what I mean below.

![bg 2](https://user-images.githubusercontent.com/26412274/29840002-6719a72a-8cce-11e7-8585-d57bf5e03544.png)

@adavila17 is of the opinion the latter issue isn't that important, so I'm more concerned about the first!

**Comment by lisajohnson11** [comment]
I'm moving this to a higher priority. Client just notified me that they are starting to release schedules and would like to have more templates for that reason soon.

**Comment by Aubron** [comment]
This is (finally) being merged as is on Monday. @lisajohnson11 - can we reach out and say sorry for this?

**Comment by lisajohnson11** [comment]
Yes I will let them know. I think this got pushed to make way for the large (extra-wide) schedule template, but I will still let them know.

**Comment by adavila17** [comment]
preview image added
