### ISSUE TITLE
FSU QuoteShot

### ISSUE THREAD

**Issue by adavila17** [Aubron/scoreshots-templates#52]
@ValentineRain test temp ID: 650

![fsu_quoteshot](https://user-images.githubusercontent.com/26416133/29880179-254715c4-8d75-11e7-8150-22c11cfd81f2.jpg)

**Comment by ValentineRain** [comment]
This template can't be opened; ScoreShots crashes with the following PHP error. I believe last time this was due to something on the admin side concerning a missing ScoreShots logo.

Can you take a look at this, @adavila17 , to determine if this needs to be escalated to development?

![php error](https://user-images.githubusercontent.com/26412274/29935398-a0c4ece4-8e4c-11e7-9164-077a7c4b2999.png)

**Comment by ValentineRain** [comment]
So Adam has resolved this with a band-aide.
The issue was that this template contains no shape layer. His solution was to add a very small, thin shape to the template somewhere it won't be noticed. It's a clever solution but I don't like it because it will in some cases become a visible imperfection.

I intend to scoot this by @Aubron shortly to consider a fix for this sort of template.

**Comment by ValentineRain** [comment]
@adavila17 Adam has also noticed that once he adds a shape layer, he can then remove it and it works fine.
So now we can make the template work, but this is still weird. It has significantly reduced the priority of this thing, though, and can maybe be left as an unresolved quirk.

Good detective work, Adam!

**Comment by ValentineRain** [comment]
Perfect. Works as expected.
After @adavila17 makes a preview image, this is good to go and can be closed.

**Comment by adavila17** [comment]
preview added
