### ISSUE TITLE
FSU Big Play: Goal 

### ISSUE THREAD

**Issue by lisajohnson11** [Aubron/scoreshots-templates#58]

**Comment by adavila17** [comment]
![fsu_scoreshot2](https://user-images.githubusercontent.com/26416133/29929943-f5e603b4-8e3a-11e7-8c06-0912033a3ab4.jpg)

@lisajohnson11 this is ready for client

**Comment by lisajohnson11** [comment]
Approved by the client 9/12 email.

**Comment by adavila17** [comment]
@ValentineRain test temp ID: 670

**Comment by ValentineRain** [comment]
This one works perfectly. 

The default text, however, does still read "Clara Robbins" like in the preview image. I know that this is in line with what FSU asked you for, but I would like to replace that default text with "ATHLETE NAME". The reason why is because the person using this template might not be the same person who requested it, and this simple change will reduce the chances of the client accidentally not changing the name because they forgot, and don't personally know the athlete.

Also it needs a preview image!
